#pragma once

// Per-(table, primary_key) row cache. Distinct from QueryCache:
//   - QueryCache caches SELECT result *sets* keyed by SQL+params; values
//     are immutable shared_ptrs and eviction never blocks reads.
//   - EntityCache caches *single rows* keyed by primary key, and the row
//     can be written from the request path (entity write absorbs into
//     RAM, batch writer drains to PG later). Dirty rows can't be evicted
//     until their write has been flushed.
//
// Faz 3 scope:
//   - per-table sharded slot table
//   - dirty / flushing / tombstone state machine
//   - hotset pinning (manual + dynamic top-K)
//   - state vs event semantics (state coalesces by pk; event tables are
//     handled by the BatchWriter event queue, not this cache)
//   - version-aware NOTIFY reconciliation (never overwrite newer local
//     state with older remote notification)
//
// Deferred to Faz 4:
//   - typed row decoders/encoders generated by the generator
//   - preload-at-startup queries
//   - cross-shard hotset migration

#include <atomic>
#include <chrono>
#include <cstdint>
#include <memory>
#include <mutex>
#include <optional>
#include <shared_mutex>
#include <string>
#include <string_view>
#include <thread>
#include <unordered_map>
#include <vector>

#include "spido_pg/endpoint_registry.h"   // TableId, DataModel

namespace spido_pg {

struct EntityRow {
    std::string data;          // serialised row payload (caller's format)
    uint64_t    version    = 0; // monotonic version assigned by writer
    bool        tombstone  = false;
};

// Snapshot returned from get(). The shared_ptr keeps the row alive even
// if the slot gets recycled between when we returned it and when the
// caller reads it.
using EntityRowPtr = std::shared_ptr<const EntityRow>;

enum class EntityState : uint8_t {
    Clean      = 0,    // matches PG (or no record)
    Dirty      = 1,    // local write pending PG flush
    Flushing   = 2,    // BatchWriter is currently writing to PG
    Tombstone  = 3,    // local delete pending PG flush
};

struct EntityCacheConfig {
    // Total memory budget in bytes; eviction kicks in when crossed.
    size_t   max_bytes = 256ull * 1024 * 1024;
    // Number of shards. Power of two; 64 matches QueryCache.
    size_t   shards    = 64;
    // Slots per shard. Power of two.
    size_t   slots_per_shard = 1024;
    // Probe chain length.
    size_t   probe     = 16;
    // Background sweep cadence — TTL expiry + tombstone cleanup.
    uint32_t sweep_interval_ms = 1000;
};

class EntityCache {
public:
    explicit EntityCache(EntityCacheConfig cfg = {});
    ~EntityCache();

    EntityCache(const EntityCache&)            = delete;
    EntityCache& operator=(const EntityCache&) = delete;

    // Read. Returns nullptr if not in cache or tombstone'd. Hot path,
    // single shared_lock on the slot.
    EntityRowPtr get(TableId table, std::string_view pk) const;

    // Write. The row is captured into the cache; the BatchWriter then
    // drains it to PG. is_dirty=true marks the entry pinned against
    // eviction until mark_flushed() is called.
    void put(TableId table, std::string_view pk, EntityRow row,
             bool is_dirty,
             std::chrono::seconds ttl = std::chrono::seconds(0));

    // Soft delete: write a tombstone. Subsequent get() returns nullptr.
    // The tombstone itself is pinned dirty until flush so a crash recovery
    // can replay the delete to PG.
    void erase(TableId table, std::string_view pk, uint64_t version);

    // Called by the flush observer once PG has acknowledged the write.
    // The entry transitions Dirty/Flushing → Clean and becomes eligible
    // for eviction. Tombstones become evictable here too.
    void mark_flushed(TableId table, std::string_view pk, uint64_t version);

    // Called by the NOTIFY listener. Updates the local copy ONLY if the
    // incoming version is strictly newer than the local version — this
    // is the "never overwrite newer local dirty state with older NOTIFY"
    // guarantee from the spec.
    void notify_remote_version(TableId table, std::string_view pk,
                               uint64_t remote_version);

    // Pin a row so eviction never picks it up. Use for hotset entries
    // identified at startup or by the top-K promoter.
    void pin  (TableId table, std::string_view pk);
    void unpin(TableId table, std::string_view pk);

    // Stats — exposed by the metrics endpoint.
    struct Stats {
        uint64_t entries = 0;
        uint64_t dirty   = 0;
        uint64_t bytes   = 0;
        uint64_t hits    = 0;
        uint64_t misses  = 0;
        uint64_t evictions = 0;
        uint64_t tombstones = 0;
    };
    Stats stats() const;

private:
    struct alignas(64) Slot {
        std::atomic<uint64_t>                   hash{0};   // 0=empty
        mutable std::shared_mutex               mtx;
        TableId                                 table = 0;
        std::string                             pk;
        EntityRowPtr                            row;
        EntityState                             state = EntityState::Clean;
        bool                                    pinned = false;
        uint64_t                                version = 0;
        std::chrono::steady_clock::time_point   expires_at{};
        mutable std::atomic<uint64_t>           last_access{0};
        size_t                                  size_bytes = 0;
    };

    // Slot has a shared_mutex which isn't movable; vector<Slot>::resize()
    // would require move-construction. Use a raw heap array via
    // unique_ptr<Slot[]> so the slots are default-constructed in-place
    // and never move.
    struct Shard {
        std::unique_ptr<Slot[]>  slots;
        size_t                   n_slots = 0;
        std::atomic<size_t>      bytes{0};
        // Counter is bumped on every read for LRU ordering. Marked
        // mutable so const get() can update it.
        mutable std::atomic<uint64_t>  counter{0};
    };

    void   sweep_loop();
    static uint64_t key_hash(TableId table, std::string_view pk) noexcept;
    Shard& shard_for(uint64_t h);
    const Shard& shard_for(uint64_t h) const;

    EntityCacheConfig                       cfg_;
    std::vector<std::unique_ptr<Shard>>     shards_;
    size_t                                  shard_mask_;
    size_t                                  slot_mask_;

    mutable std::atomic<uint64_t>           hits_{0};
    mutable std::atomic<uint64_t>           misses_{0};
    mutable std::atomic<uint64_t>           evictions_{0};
    mutable std::atomic<uint64_t>           tombstones_{0};

    std::thread                             sweep_thread_;
    std::atomic<bool>                       stop_{false};
};

} // namespace spido_pg
